### ISSUE TITLE
Project import not load

### ISSUE THREAD

**Issue by BrianGiannini** [gmuth/ipp-client-kotlin#1]
I tried to implement this lib on an Android project in the gradle app file with :
`implementation 'de.gmuth.ipp:ipp-client-kotlin:1.4'`
But it seems that it's not recognized : 

> Failed to resolve: de.gmuth.ipp:ipp-client-kotlin:1.4

Is this project still up ? How I can import it properly ?

**Comment by gmuth** [comment]
I've updated section Artifacts in the documentation. What maven repos are used by your build?

The artifact` 'de.gmuth.ipp:ipp-client-kotlin:1.6'` is only available in this github maven repo:
```
maven {
  url = uri("https://maven.pkg.github.com/gmuth/ipp-client-kotlin")
  credentials {
     username = "login.."
     password = "token.."
  }
}
```

Obviously my tests use my account, which has read permissions. I would hope that any github account is authorized to read the repo as well. Please configure your github account and token and try again.

**Comment by BrianGiannini** [comment]
But why do we have to add those credentials? Could it just be uploaded on a public maven repos?

**Comment by gmuth** [comment]
This is just how GitHub Packages work right now. Maybe they support public access in the future.
[Using a library from GitHub Packages within an Android Application](https://proandroiddev.com/publishing-android-libraries-to-the-github-package-registry-part-1-7997be54ea5a) works well.
The library is currently not available in other repos.

You can also `git clone` the latest sources and install the library into your local repo: `gradlew publishToMavenLocal`

**Comment by gmuth** [comment]
The library is now publicly available at maven central.
