### ISSUE TITLE
Unable to add the ipp network printer to cup server 

### ISSUE THREAD

**Issue by Krishnanudhaya** [gmuth/ipp-client-kotlin#10]
Hi Team,

I would like to add the network printer to cups server using http call ( printer_host_name, port).

I couldn't find the way to add the printer to cupserver from cups api documentation.

Please share the cup api which allows to add ipp network printer into cups and share the different approaches to connect the printer.

Currently, I have connecting the cup server with cups4j library through java.

Additional Links :
https://github.com/OpenPrinting/cups/issues/514
https://github.com/OpenPrinting/cups/issues/516

Thanks

**Comment by gmuth** [comment]
That's an interesting use case we can look into. The operation Cups-Add-Modify-Printer is documented here: https://www.cups.org/doc/spec-ipp.html#CUPS_ADD_MODIFY_PRINTER
You should use the exchange-IppRequest-for-IppResponse API to create the appropriate request and receive the response. It looks like you can optionally upload a PPD file along.
I am not very familiar with this operation and have further questions.
Usually you add a printer to CUPS via GUI or command line. 
Also sometimes installing a driver is required. Installing extra software is not possible via CUPS ipp API.
Does the printer to be added support IPP?
Please provide an example of a cli command which you try to convert into an ipp command.

**Comment by gmuth** [comment]
[CupsClient](https://github.com/gmuth/ipp-client-kotlin/blob/master/src/main/kotlin/de/gmuth/ipp/client/CupsClient.kt) [now supports](https://github.com/gmuth/ipp-client-kotlin/commit/4249c694f270b745629ba3d63aad911f64d24adc) `addModifyPrinter()` and `deletePrinter()`:

```
CupsClient().addModifyPrinter(
  "duster", URI.create("ipp://192.168.2.144"), "MyDuster", "Downstairs", "everywhere"
)
```

The operation supports PPD file upload via optional parameter `ppdInputStream`.
After adding the cups printer it can become fully operational via:

```
val myDuster = cupsClient.getPrinter("duster")
myDuster.enable()
myDuster.resume()
```

**Comment by Krishnanudhaya** [comment]
Thank you for your update @gmuth

**Comment by gmuth** [comment]
[Latest addition to CupsClient](https://github.com/gmuth/ipp-client-kotlin/commit/2723e929ad16480c35de2fecba6ee844f96c5722)!

To setup printers supporting [IPP Everywhere](https://www.pwg.org/ipp/everywhere.html) use this operation.
CUPS will query the printer and generate a PPD accordingly.

```
setupIppEverywherePrinter(
  "inky2",
  URI.create("ipp://inky2.local"
  "MyInky2",
  "MyRoom"
)
```

**Comment by gmuth** [comment]
The operation has been renamed to `createIppEverywherePrinter`
