### ISSUE TITLE
'copies' not working as expected

### ISSUE THREAD

**Issue by fushengss** [gmuth/ipp-client-kotlin#18]
Because setting the number of copies through copies of ipp-client will cause multiple copies of a certain page to be printed before starting the next one, which is inconsistent with my expectation of finishing one copy and then printing the second copy, so I chose to use a for loop. The method calls multiple print tasks, but an error is reported
![image](https://github.com/gmuth/ipp-client-kotlin/assets/56241904/5a252b02-b611-4dac-846d-2511d92825c7)
![image](https://github.com/gmuth/ipp-client-kotlin/assets/56241904/73124013-fb1b-446f-9f2d-0dfab82e28a1)

**Comment by gmuth** [comment]
1. The behavior of the copies attribute is defined in [RFC 8011](https://datatracker.ietf.org/doc/html/rfc8011#section-5.2.5):

"On many devices, the supported number of collated copies will be
   limited by the number of physical output bins on the device and can
   be different from the number of uncollated copies that can be
   supported."
   
When using this attribute your printer really should have multiple output bins. I think historically processing and rendering a page was more expensive than physical printing. So the rendered page in memory could can be printed multiple times on consecutive media sheets. If you have only one output bin this makes only sense for 1 page documents from my point of view.

2. multiple-document-handling

If you printer supports multiple documents you should look into configuring the [handling for multiple documents](https://datatracker.ietf.org/doc/html/rfc8011#section-5.2.4).

3. bad request

The request is okay assuming the printer supports the features you are trying to use. Please provide the full exception, error message, unsupported attributes and log in text form (not screen shots). "Bad Request" usually means the printer is not happy about some request attributes/features you are using and not willing to accept your request. I'd be happy to help if you provide the required response and error details. The response should include the details of why the printers classifies the request as "bad".

**Comment by gmuth** [comment]
Another remark about your code. Inputstreams can only be consumed/read once. So only the first printJob execution will be able to forward a document to the printer. If you want to access a file over and over again within a loop, you have to get/create a new/fresh Inputstream for each run. Or instead you could hand over the File to the printJob operation because I've provided a method signature for File as well.

**Comment by gmuth** [comment]
Attribute "multiple-document-handling" is [now](https://github.com/gmuth/ipp-client-kotlin/commit/f57c8cffda771acf091df3d6ae20a1aec4a05285) supported:

```
copies(5),
MultipleDocumentHandling.SeparateDocumentsCollatedCopies
```
