### ISSUE TITLE
'application/pdf' is not supported

### ISSUE THREAD

**Issue by fromdestiny** [gmuth/ipp-client-kotlin#2]
First of all Thank you for sharing good library!!

I success to print image using this library.
but When I try to print pdf, I failed.

According to log, my print seems not  supported 'application/pdf'.

"document-format-supported (1setOf mimeMediaType) = application/octet-stream,image/pwg-raster,image/urf,image/jpeg"

Is there anyway to print pdf using ipp?

**Comment by gmuth** [comment]
Unfortunately this library does not support rendering PDF documents.
You could try [JIPP jrender](https://github.com/HPInc/jipp) which uses [Apache PDFBox](https://pdfbox.apache.org) to render [PDF as PWG](https://github.com/HPInc/jipp/blob/master/sample/jrender/src/main/java/sample/jrender/Main.java).

**Comment by fromdestiny** [comment]
Thank you for reply.

I use JIPP jrender to convert pdf to pwg. 
Then I success to print by this library!

**Comment by gmuth** [comment]
[Simon Scholz](https://github.com/SimonScholz) has created a tutorial how to render PWG to PDF and submit the stream to a printer:
https://simonscholz.dev/tutorials/ipp-print-java-kotlin

**Comment by gmuth** [comment]
Manufacturers usually don't list exactly what document formats their printers support.
I've created a repository [document-format-supported](https://github.com/gmuth/document-format-supported/) to fill this gap.
