### ISSUE TITLE
java.io.IOException: Failed to create directory CUPS/192.168.0.91

### ISSUE THREAD

**Issue by Badouu** [gmuth/ipp-client-kotlin#22]
Hello. When I specify the CUPS server address. I get the following message:
java.io.IOException: Failed to create directory: CUPS/192.168.0.91

**Comment by gmuth** [comment]
Some CupsClient operations save files to `cupsClientWorkDirectory`.
By default the CupsClient creates directory "CUPS/${cupsUri.host}" in the current directory where the application has started. The application was expected to have write permissions on the filesystem.

I've commit and pushed a change to fix this issue. Please pull, build and test again.

**Comment by Badouu** [comment]
Hello, thank you very much for your reactivity. The error is gone. I'll test in more detail tomorrow to see if everything is ok.

**Comment by gmuth** [comment]
In case your application calls `...save...` methods it needs to make sure the directory exists. e.g. by successfully calling
`cupsClient.cupsClientWorkDirectory.mkdirs()`
