### ISSUE TITLE
de.gmuth.ipp.client.IppExchangeException: Print-URI failed: 'server-error-operation-not-supported', Print-URI not supported.

### ISSUE THREAD

**Issue by Badouu** [gmuth/ipp-client-kotlin#24]
Hello, I'm trying to run a test print but I get the following error: 
de.gmuth.ipp.client.IppExchangeException: Print-URI failed: 'server-error-operation-not-supported', Print-URI not supported.
Do you know what could be causing it?

**Comment by gmuth** [comment]
The printer/server does not support the optional operation 'Print-URI'. From my knowledge only few old printers support this operation (e.g. HP LaserJet 100 colorMFP M175nw). Current IPP implementations do not implement this operation as it is deprecated according to this document:
https://ftp.pwg.org/pub/pwg/ipp/registrations/reg-ippdepuri10-20211215.pdf.

In case you use CUPS, it does not support this operation either according to their documentation at
https://www.cups.org/doc/spec-ipp

**Comment by Badouu** [comment]
Thank you for your quick feedback, I'll look into it.
