### ISSUE TITLE
de.gmuth.ipp.core.IppException: Attribute 'notify-lease-duration' not found in group subscription-attributes-tag

### ISSUE THREAD

**Issue by Badouu** [gmuth/ipp-client-kotlin#25]
Hello, I get this error with the command :
job.subscription?.pollAndHandleNotifications { println(it) }

**Comment by gmuth** [comment]
Does your application communicate with a CUPS server?

It might help to call `updateAttributes()` of IppSubscription before calling `pollAndHandleNotifications()`.

I have changed the handling for subscription-expiry-checking. Please pull the main branch, build the lib and test again.
In case of errors please provide the full stacktrace.

**Comment by Badouu** [comment]
Hello, yes my application communicates with a CUPS server. Okay, I'll do the test and get back to you.

**Comment by gmuth** [comment]
My tests were successful, so the bug is now fixed (for versions after 3.1)

**Comment by Badouu** [comment]
I've also tested it, and I don't have any more problems. Thank you.
