### ISSUE TITLE
Printer is unable to print some PDF documents

### ISSUE THREAD

**Issue by GrupoRomano** [gmuth/ipp-client-kotlin#27]
Hello! I am having some difficulties sending documents in PDF format... Some PDF documents are sent and printed successfully, while others receive an error code as if the document was in the wrong format

**Comment by GrupoRomano** [comment]
The question is, is there any way to treat or standardize the PDFs so they can be sent successfully? I'm sure they are correct because I can print them normally through windows

**Comment by gmuth** [comment]
Sometimes I have similar issues with pdf documents not being supported by the pdf engine of the printer. There are various tools for sure - I personally just use poppler utils pdftocairo with -pdf option.
https://manpages.debian.org/testing/poppler-utils/pdftocairo.1.en.html#pdf

**Comment by gmuth** [comment]
Sometimes printers support various pdf formats and show this in the printer attributes. I suggest you run the Inspection workflow from IppInspector and provide log and ipp messages.
