### ISSUE TITLE
Canon Selphy Printer Image Size

### ISSUE THREAD

**Issue by janjanmedinaaa** [gmuth/ipp-client-kotlin#30]
I got it connected and working on my Canon Selphy Printer CP1500 but it doesn't print full size. I tried getting the `ippPrinter.mediaSizeSupported` and got `[10000x14800, 8900x11900, 5400x8600, 5300..10200x8500..15300]` which I think is correct. I'm just not sure how to print it on the correct size.

```kotlin
val job = ippPrinter.printJob(
    imageFile,
    jobName(imageFile.name),
    DocumentFormat.JPEG,
    printerResolution(300, IppResolution.Unit.DPI),
    PrintQuality.High,
    MediaSize(10000, 14800)
)
```

**Comment by janjanmedinaaa** [comment]
Okay I got the Media Supported List `[jpn_hagaki_100x148mm, om_dsc-photo_89x119mm, om_card_54x86mm, custom_min_53x85mm, custom_max_102x153mm]` and tried setting it on the print job but it's still not working.

```kotlin
ippPrinter.printJob(
    imageFile,
    jobName(imageFile.name),
    DocumentFormat.JPEG,
    printerResolution(300, IppResolution.Unit.DPI),
    PrintQuality.High,
    Media("jpn_hagaki_100x148mm")
)
```

**Comment by gmuth** [comment]
Try what's documented in the README.md:

```
MediaCollection(
  MediaSize(width, width * image.height / image.width),
  MediaMargin(300) // 3 mm
)
```
