### ISSUE TITLE
Create jar files for source files (and javadoc) to promote ease of use of API from IDE 

### ISSUE THREAD

**Issue by knowbits** [gmuth/ipp-client-kotlin#9]
Having source files (and javadoc) available as jars would make it easier to use the API from an IDE.

**Comment by gmuth** [comment]
I've updated the gradle build file. The default task `assemble` now produces the (kotlin) source and javadoc jars.

**Comment by knowbits** [comment]
That's quick!

Gave it a try with a local installation into Maven.

In VS Code, documentation show up when I hover 👍

When I go into a clasd or method (F12) the.class file is opened. I don't
know if you use VS Code (most seasoned Jave devs use IDEA, I guess), but do
you know how to make VS Code open the .kt file instead?

Best, Erlend

**Comment by gmuth** [comment]
I don't use VS Code and can not provide a solution for your question.

**Comment by knowbits** [comment]
Support for Kotlin in VS Code seems to be lacking atm.
